### ISSUE TITLE
where to put the sample files?

### ISSUE THREAD

**Issue by prog-ape** [niknah/ComfyUI-F5-TTS#12]
![image](https://github.com/user-attachments/assets/d6ed2d10-b3a0-4202-ba70-85f54814c797)

**Comment by niknah** [comment]
In the "input" folder.  And also the .txt file which contains what you had said in the .wav file.
So you have...
```
F5TTS_test_en_1_ref_short.wav
F5TTS_test_en_1_ref_short.txt
```

**Comment by prog-ape** [comment]
If Chinese is used, an encoding exception will occur: UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 14: illegal multibyte sequence

F5TTS_test_zh_1_ref_short.txt
F5TTS_test_zh_1_ref_short.wav

**Comment by niknah** [comment]
I don't know why it's trying to read it in gbk.  The default in python is utf-8.  What did you use to edit the text file?   If you're in windows can you save it as UTF-8 in notepad?
![image](https://github.com/user-attachments/assets/8b2e469a-de74-4998-a9fd-7dce7f64e0a9)

**Comment by prog-ape** [comment]
Thanks for your answer, I will try to re-code

**Comment by prog-ape** [comment]
> I don't know why it's trying to read it in gbk. The default in python is utf-8. What did you use to edit the text file? If you're in windows can you save it as UTF-8 in notepad? ![image](https://private-user-images.githubusercontent.com/934114/387854920-8b2e469a-de74-4998-a9fd-7dce7f64e0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODkxNTgsIm5iZiI6MTczMjA4ODg1OCwicGF0aCI6Ii85MzQxMTQvMzg3ODU0OTIwLThiMmU0NjlhLWRlNzQtNDk5OC1hOWZkLTdkY2U3ZjY0ZTBhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwNzQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjBhZDgwMmYwY2E1Y2E3ODU5YTM3NjZjNTdkMWRkNGNiOTRhMzkxMzU3ZGFhZjViMGY3MzJmNGNhZjlkNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rsz-6D0UAon4Ln1f-5NJPJ_CWfdB0Qw_3EP5lCkcQ6Q)


solving this problem

    def load_voice_from_file(self, sample):
        input_dir = folder_paths.get_input_directory()
        txt_file = os.path.join(
            input_dir,
            F5TTSAudio.get_txt_file_path(sample)
        )
        audio_text = ''
        with open(txt_file, 'r', encoding='utf-8') as file:
            audio_text = file.read()

        audio_path = folder_paths.get_annotated_filepath(sample)
        return F5TTSCreate.load_voice(audio_path, audio_text)
