### ISSUE TITLE
Where should I put the downloaded model?

### ISSUE THREAD

**Issue by deki18** [niknah/ComfyUI-F5-TTS#13]
Where should I put the downloaded model?

**Comment by niknah** [comment]
The model is automatically downloaded.   You only need to download the [voice samples](https://github.com/niknah/ComfyUI-F5-TTS/tree/main/examples) or your own voice into the "input" folder.


If you want to change where the model is automatically downloaded, set the environment CACHED_PATH_CACHE_ROOT before running ComfyUI like...

```
export CACHED_PATH_CACHE_ROOT="ComfyUIPath/models/F5"
python3 main.py
```

**Comment by niknah** [comment]
commit  3bca21f0c428e9cbd58031be4766dad4ad51884a adds this feature.  

You can put the model & vocab txt files into "models/checkpoints/F5-TTS" folder if you have any more models.  Name the .txt vocab file and the .pt model file the same names.  Press "refresh" and it should appear under the "model" selection.
