### ISSUE TITLE
error

### ISSUE THREAD

**Issue by T8mars** [niknah/ComfyUI-F5-TTS#6]
![image](https://github.com/user-attachments/assets/8cbd2865-c98b-442c-9f52-a35c7805dcb8)
I have installed all requirements

**Comment by niknah** [comment]
How did you get this?  With comfy manager or with "git" command line or "install via git url" in comfy manager?

It's best to install it from comfy manager.

It should have checked out the F5-TTS in custom_nodes/ComfyUI-F5-TTS/F5-TTS

If you had installed it not with comfy manager.  Go to the command line and update the submodules...
```
cd custom_nodes/ComfyUI-F5-TTS
git submodule update --init --recursive
```

**Comment by BecarefulW** [comment]
我是用comfy manager安装的，也出现同样问题
File "G:\AI\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\ComfyUI\custom_nodes\ComfyUI-F5-TTS\__init__.py", line 2, in <module>
    from .F5TTS import F5TTSAudio, F5TTSAudioInputs
  File "G:\AI\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5TTS.py", line 20, in <module>
    from model import DiT,UNetT # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'model'

git submodule update --init --recursive后也无法解决

**Comment by niknah** [comment]
此文件存在吗？“custom_nodes/ComfyUI-F5-TTS/F5-TTS/model/__init__.py”

**Comment by bob83111** [comment]
> 此文件存在吗？“custom_nodes/ComfyUI-F5-TTS/F5-TTS/model/**init**.py”

大佬我是秋叶包，我也装了所有依赖，然后也是加载不了节点。这个init文件有的。报错信息如下：


Cannot import E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-F5-TTS module for custom nodes: No module named 'jax.numpy'; 'jax' is not a package

**Comment by niknah** [comment]
> Cannot import E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-F5-TTS module for custom nodes: No module named 'jax.numpy'; 'jax' is not a package

https://github.com/niknah/ComfyUI-F5-TTS/issues/10

**Comment by niknah** [comment]
This was caused by F5-TTS re-arranging their repository.  I didn't check. 
 Update it and try now. Should work.

**Comment by niknah** [comment]
commit 3bca21f0c428e9cbd58031be4766dad4ad51884a, reopen if you think it's not working

**Comment by bob83111** [comment]
> 提交[3bca21f](https://github.com/niknah/ComfyUI-F5-TTS/commit/3bca21f0c428e9cbd58031be4766dad4ad51884a)，如果您认为它不起作用，请重新打开

我更新了，还是不行。报错还是那个JAX。  提交3bca21f 是什么意思？
