### ISSUE TITLE
Add inputs for audio and text.

### ISSUE THREAD

**Issue by valandyr** [niknah/ComfyUI-F5-TTS#7]
Hello, thank you for taking the time to make this repo.

I think that adding regular comfyui inputs to the node would streamline generating voices.
For instance we could use a load audio node, a whisper transcribe node (already available custom node) and and have outputs fed to the F5-TTS node.
This approach would help with batch generation and will even be superior to the gradio app because in comfyui it is trivial to unload whisper model before loading F5 to further lower vram requirements.

**Comment by niknah** [comment]
Thanks for telling about this.  Very useful.  I have added a new node to accept an audio + text input.

Example workflow...
https://github.com/niknah/ComfyUI-F5-TTS/blob/main/examples/F5TTS_whisper_workflow.json

**Comment by valandyr** [comment]
Thank you very much! Its great!
