### ISSUE TITLE
Request: Add option to use the E2 model

### ISSUE THREAD

**Issue by valandyr** [niknah/ComfyUI-F5-TTS#9]
After some testing in gradio, i found that some voices(anger/yell) works best with the E2 model.
Tried to change the `repo_name` and `exp_name` variables to E2. It downloads the model then execution is borked.

**Comment by valandyr** [comment]
Also when using `midpoint` vs `euler` it results in considerably less artifacts, although it runs slower. Having those parameters exposed will help in some cases.

**Comment by niknah** [comment]
If you want to try other options, ODE method, relative_tolerance, absolute_tolerance.  Use this branch...
https://github.com/niknah/ComfyUI-F5-TTS#2024_11_test_params

But I did not hear much difference with those settings.

I found out that F5-TTS is not using a seed so you get a random new speech every time you run it.
Changing the seed made a lot of difference.  I have added a seed value there.  Attached example workflow.
[workflow_f5tts_seed_test.json](https://github.com/user-attachments/files/17659684/workflow_f5tts_seed_test.json)

**Comment by niknah** [comment]
commit 8004747cf611a00bb3d33bce59b62b47ebf944ba
